Repository packit/deployment, pull requests merged in 2022-10, with the labels that each got.

#386 chore: move from auto-stage to auto-prod
  vars/fedora-source-git/stg_template.yml
  vars/packit/stg_template.yml
  vars/stream/stg_template.yml
Labels: ready-for-review, mergeit, 🌞 friday 🤟

#352 Add fluentd sidecar to worker
  README.md
  docs/logs.md
  openshift/packit-worker.yml.j2
  openshift/secret-splunk.yml.j2
  playbooks/deploy.yml
  vars/fedora-source-git/prod_template.yml
  vars/fedora-source-git/stg_template.yml
  vars/packit/prod_template.yml
  vars/packit/stg_template.yml
  vars/stream/prod_template.yml
  vars/stream/stg_template.yml
  vars/template.yml
Labels: ready-for-review

#390 Add `render-secrets-from-templates` target
  Makefile
  docs/allow-custom-copr-projects.md
  playbooks/render_secrets_from_templates.yml
  scripts/render_secrets_from_templates.sh
  scripts/update_bw_secret.sh
  secrets/README.md
Labels: mergeit

#391 Update Splunk Howto
  docs/logs.md
Labels: mergeit

#392 Don't specify command to run in packit-service-fedmsg pod
  openshift/packit-service-fedmsg.yml.j2
  playbooks/check.yml
  playbooks/cleanup.yml
  playbooks/deploy.yml
  playbooks/import-images.yml
  playbooks/tasks/project-dir.yml
  playbooks/zuul-deploy.yml
  playbooks/zuul-secrets.yml
  roles/generate-secrets/tasks/project-dir.yml
Labels: mergeit

#393 Disable OpenSSL system configs when downloading secrets
  Makefile
  secrets/README.md
Labels: mergeit
